config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'students#new'
  get '/students/new', to: 'students#new'
  post '/students', to: 'students#create'
  get '/teachers/new', to: 'teachers#new'
  post '/teachers', to: 'teachers#create'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @placeholder_name = 'Jane'
    @placeholder_color = 'Blue'
    @placeholder_year = '2018'
  end

  def create
    @full_name = params[:full_name]
    @fav_color = params[:fav_color]
    @grad_year = params[:grad_year]
    render 'show'
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    @placeholder_course = '186'
  end

  def create
    @full_name = params[:full_name]
    @course = params[:course]
    @grade_level = params[:grade_level]
    render 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fa16Hw3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/new.html.erb
<form action="/students" method="POST">
  <label>Full name</label>
  <input 
    name="full_name" 
    placeholder=<%= @placeholder_name %> 
    type="text"></input>
  <label>Favorite Color</label>
  <input
    name="fav_color"
    placeholder=<%= @placeholder_color %>
    type="text"
  >
  </input>
  <label>Graduation Year</label>
  <input 
    name="grad_year" 
    placeholder=<%= @placeholder_year %> 
    type="text"></input>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <button type="submit">Create student</button>
</form>
<br><br>
<%= link_to "Make a teacher form", teachers_new_path %>

app/views/students/show.html.erb
<div>
  <h2>Welcome New Students!</h2>
  <h4>Full name</h4>
  <h3>
    <%= @full_name %>
  </h3>
  <h4>Favorite Color</h4>
  <h3>
    <%= @fav_color %>
  </h3>
  <h4>Graduation Year</h4>
  <h3>
    <%= @grad_year %>
  </h3>
  
</div>

<br><br>
<%= link_to "Make a teacher form", teachers_new_path %>

app/views/teachers/new.html.erb
<form action="/teachers" method="POST">
  <label>Full name</label>
  <input name="full_name" type="text"></input>
  <label>Course name</label>
  <input
    name="course"
    placeholder=<%= @placeholder_course %>
    type="text"
  >
  </input>
  <label>Grade level</label>
  <input name="grade_level" type="text"></input>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <button type="submit">Create teacher</button>
</form>
<br><br>
<%= link_to "Make a student form", students_new_path %>

app/views/teachers/show.html.erb
<div>
  <h2>Welcome TEACHERS!</h2>
  <h4>Full name</h4>
  <h3>
    <%= @full_name %>
  </h3>
  <h4>Course</h4>
  <h3>
    <%= @course %>
  </h3>
  <h4>Grade level</h4>
  <h3>
    <%= @grade_level %>
  </h3>
</div>
<br><br>
<%= link_to "Make a student form", students_new_path %>